### ISSUE TITLE
Undo Feature in Room Editor

### ISSUE THREAD

**Issue by ajilpappachan** [ct-js/ct-js-old#259] opened 2020-12-26 15:52 UTC
Hi. I can't seem to undo when I make a mistake inside the room editor. I feel like this is a very important feature to have. Also, the ability to copy-paste or duplicate selected elements inside the editor would be a huge lifesaver.

**Comment by CosmoMyzrailGorynych** [comment] 2020-12-28 01:10
Duplicate of #76

**Closed as completed by CosmoMyzrailGorynych** 2020-12-28 01:10 UTC
Labels: state:duplicate
