### ISSUE TITLE
MacOS - Black bar in texture editor making editing difficult

### ISSUE THREAD

**Issue by limitlis** [ct-js/ct-js-old#292] opened 2021-07-09 15:14 UTC
**Describe the bug**
On MacOS v.1.7.0 there is a black bar that spans the entire width of the editor while you are in the Textures editor.

**To Reproduce**
1. Go to Textures tab/view.
2. Generate a placeholder or edit an existing texture.
3. Resize window bigger and/or smaller.
4. See bar appear in larger editor windows. It goes away if I make the screen small

I have noticed a black bar also appear when changing settings for mods. But in those instances it appears when changing a setting and quickly disappears (almost like a weird loading/status bar.) But in texture editor it's persists.

**Expected behavior**
The black bar should not be there, as it impedes editing. 

**System information report**
Ct.js v1.7.0 😽 (packaged)
NW.JS v0.51.2
Chromium v88.0.4324.182
Node.js v15.8.0
Pixi.js v5.1.2

WebGL available
WebGL vendor Intel Inc.
WebGL renderer Intel(R) Iris(TM) Plus Graphics 655
OS darwin x64 // Darwin 19.6.0

**Screenshots (recommended)**
Screenshot of the persistent bar in text editor
![image](https://user-images.githubusercontent.com/868862/125097706-40f7f500-e08b-11eb-9eed-8900306bec27.png)

Video of the black bar while editing mod settings.
https://user-images.githubusercontent.com/868862/125100008-7c93be80-e08d-11eb-8072-9c605fd67374.mov

**Example project (strongly recommended)**
[test.ict.zip](https://github.com/ct-js/ct-js/files/6792282/test.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment] 2021-07-10 03:05
Duplicate of #276

**Closed as completed by CosmoMyzrailGorynych** 2021-07-10 03:05 UTC
Labels: state:duplicate

**Comment by limitlis** [comment] 2021-07-10 06:15
ah, sorry about that!
