### ISSUE TITLE
Add an option to organize textures and copies by group or category

### ISSUE THREAD

**Issue by rBok6** [ct-js/ct-js-old#189] opened 2020-05-08 17:40 UTC
**Describe the current state of the problem**
Currently if you have lots of textures or copies it's very difficult to find all the ones you need for your project. You have a search box to find copies but I think It would be better if a group or category system is implemented.

**Describe the solution you'd like**
For example, in the textures tab there should be an option called "create texture group or category" and after creation a user should be able to drag and drop specific textures to that group or category. So when the user is on the Room editor, on the Copies tab, that group or category should appear as a collapsible with the name of the group that the user created along with all the textures that the user added to that group /category. I think this is a good idea to organize projects with different types of textures or copies.

**Describe alternatives you've considered (optional)**
I think this implementation could also work with the Types tab, to organize copies too.

**Comment by CosmoMyzrailGorynych** [comment] 2020-05-09 12:29
Duplicate of #75

**Closed as completed by CosmoMyzrailGorynych** 2020-05-09 12:29 UTC
Labels: state:duplicate, type:enhancement
