### ISSUE TITLE
Custom properties is no longer working

### ISSUE THREAD

**Issue by xtremezero** [ct-js/ct-js-old#416] opened 2023-04-30 16:46 UTC
**Describe the bug**
Custom properties for Copies is no longer appearing in the Room screen, I can see the button that creates custom properties, but it doesn't add or show any screen

**To Reproduce**
0. Create a template and it to a room
1. Go to the room and add a copy
2. Click on the copy to see its information
3. in the bottom of the information screen , click [+ADD PROPERTY] 
4. nothing happen in version 3.2 , while in earlier versions I was able to add properties

**Expected behavior**
To be able to add properties

**System information report**
Ct.js v3.2.0 😽 (packaged)

NW.JS v0.67.1
Chromium v104.0.5112.80
Node.js v18.7.0
Pixi.js v5.3.11

WebGL available
WebGL vendor Google Inc. (Intel)
WebGL renderer ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.22621

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/10077145/235365407-03cfa3f1-f784-4571-90e6-c97ba39e01d9.png)

**Comment by CosmoMyzrailGorynych** [comment] 2023-08-03 12:02
Duplicate of https://github.com/ct-js/ct-js/issues/408; fixed in Nightly builds.

**Closed as not planned by CosmoMyzrailGorynych** 2023-08-03 12:02 UTC
Labels: type:bug, state:duplicate
