### ISSUE TITLE
3.3.0 project cannot be opened in 4.0.2

### ISSUE THREAD

**Issue by StepanMynarik** [ct-js/ct-js-old#507] opened 2024-03-27 22:45 UTC
**Describe the bug**
Hi,

I have customized the base template project with my son, initially on 3.2.0, then updated to 3.3.0 with no difficulty.

Today I updated to 4.0.2 but I can't open the project in this version, getting `TypeError: Cannot get properties of undefined (reading 'length')` and I simply stay on the start screen then.

**To Reproduce**
1. Download the attached project
2. Open "zip" (portable) version of ct.js 4.0.2
3. Try opening the project from the start screen

**Expected behavior**
Project will be opened. It will be possible to start the game and hear sounds when jumping etc.

**System information report**
Ct.js v4.0.2 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGPU UNAVAILABLE
WebGL available
WebGL vendor Google Inc. (NVIDIA)
WebGL renderer ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.22631

**Screenshots (recommended)**
![image](https://github.com/ct-js/ct-js/assets/46678816/dba057cd-bd51-4d6f-aaa4-0f242c833488)

**Example project (strongly recommended)**
[Bertas First Game.zip](https://github.com/ct-js/ct-js/files/14781924/Bertas.First.Game.zip)

**Comment by godmar** [comment] 2024-07-10 22:55
This is likely due to changes in the `sound` entries.
The code appears to assume that these entries contain a `.variants` property that is an array. This property was not present in 3.x before the change to the new sound engine.

See, for instance, [here](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/node_requires/resources/preview/sound.ts#L12) and [here](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/node_requires/resources/sounds/index.ts#L78) which contains expressions such as `sound.variants.length` or `sound.variants.push`.

@CosmoMyzrailGorynych could you fix this or advise?

We won't be able to continue to use ct.js if we can't import our 3.x project.

**Comment by godmar** [comment] 2024-07-11 02:39
Could you take a look at your project migration scripts?

You're calling `createAsset()` [here](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/js/projectMigrationScripts/4.0.0-next-3.js#L50).

I see two problems here:

1. you're calling it without a name - that causes it to [put up a prompt to the user](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/node_requires/resources/sounds/index.ts#L12) which appears random.
2. it returns a Promise, but you don't `await` it. So you treat `newSound` as though it were an object rather than a Promise. (I don't know why [`createAsset`](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/node_requires/resources/sounds/index.ts#L10-L65) is `async` in the first place - does it have to be?)

Consider this patch:

```patch
--- a/src/js/projectMigrationScripts/4.0.0-next-3.js
+++ b/src/js/projectMigrationScripts/4.0.0-next-3.js
@@ -47,15 +47,15 @@ window.migrationProcess.push({
                     delete sound[oldKey];
                 }
 
-                const newSound = createAsset();
-                delete newSound.name;
-                delete newSound.uid;
-                newSound.preload = preload;
+                async.push(createAsset(sound.name).then((newSound => {
+                    delete newSound.name;
+                    delete newSound.uid;
+                    newSound.preload = preload;
 
-                Object.assign(sound, newSound);
+                    Object.assign(sound, newSound);
 
-                async.push(addSoundFile(sound, oldFile)
-                    .then(() => fs.remove(oldFile)));
+                    return addSoundFile(sound, oldFile).then(() => fs.remove(oldFile));
+                })));
             }
         }
         if (async.length > 0) {
```
Alternatively, you could make `createAsset` synchronous if possible.

**Comment by CosmoMyzrailGorynych** [comment] 2024-07-11 07:05
> I don't know why [createAsset](https://github.com/ct-js/ct-js/blob/9c4436f6d2fb4f8f52abef7010b3dea4f7151904/src/node_requires/resources/sounds/index.ts#L10-L65) is async in the first place - does it have to be?

Yes, precisely for when the IDE needs to prompt the user for a name, plus for other async tasks like copying or converting files. The common resources API requires all asset types' modules to expose a specific interface, so all asset creations tasks are awaited.

**Comment by CosmoMyzrailGorynych** [comment] 2024-07-11 09:22
@godmar I've pushed a fix to the `develop` branch, please test the upcoming Nightly (or run from sources) to confirm/deny that the problem is solved.

**Comment by godmar** [comment] 2024-07-11 13:58
I'm testing this now; meanwhile, another error pops up for the `Berta....zip` file @StepanMynarik provided: `...mouse/module.json` not found. In commit 7db23c560e60615f2d28db696dc2e57310962e74 you removed `ct.mouse` but I don't see where this is accounted for in the migration scripts.  Do you need this:

```patch
--- a/src/js/projectMigrationScripts/4.0.0-next-1.js
+++ b/src/js/projectMigrationScripts/4.0.0-next-1.js
@@ -12,6 +12,7 @@ window.migrationProcess.push({
         }
         delete project.libs.fittoscreen;
         delete project.libs.touch;
+        delete project.libs.mouse;
         delete project.libs['sound.howler'];
         delete project.libs['sound.basic'];
 
```

**Comment by godmar** [comment] 2024-07-11 14:23
For my test game, the sound conversion aspect now appears to work, but the game itself does not. I'll show you on Discord.

*PS*: this issue turned out to be fixed as advised by disabling Vulkan and restarting ct.js

**Comment by godmar** [comment] 2024-07-13 01:40
More observations. After commit 1de688dc the game can now be imported, but there's a semantic change that causes the existing code to fail when it comes to using the sounds API.

Sounds that were marked as "background music" (`isMusic == true`) now have the `preload` flag set, whereas those that are not are not preloaded.  In the new sound implementation, it appears that it's illegal to call methods such as `sounds.playing` or `sounds.stop` on sounds that haven't been preloaded or loaded.  Sounds are loaded when they are first played, or when `sound.load` is called.

This is a breaking change - the 3.x games worked fine when these methods were called on sounds that hadn't been loaded.  I believe that perhaps the semantics of these `sounds` functions could be changed to accommodate not-yet-loaded sounds. (Also in light of `sounds.exists`, which returns true for sounds even if they haven't been loaded.)  In any event, it may be helpful to document this issue in the migration guide.

**Closed as completed** 2024-07-20 03:19 UTC
Labels: type:bug
