### ISSUE TITLE
Copy of template disappears, after using rooms variable created in rooms event, used in templates event.

### ISSUE THREAD

**Issue by 111ukasz111** [ct-js/ct-js-old#551] opened 2024-11-05 09:30 UTC
**Describe the bug**
Copy of Template disappears after using "this.speed = rooms.current.test;" rooms variable" this.test = 100;" created in rooms event.

**To Reproduce**
1. Go to rooms events.
2. Add variable " this.test = 100" in rooms event.
3. Use this variable in templates event" this.speed = rooms.current.test;".
4. Run game and this copy of template will disappears.

**Expected behavior**
This template shouldn't disappears

**System information report**
Ct.js v5.2.1 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGL available
WebGL vendor Google Inc. (NVIDIA)
WebGL renderer ANGLE (NVIDIA, NVIDIA GeForce 920M Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.19045

**Screenshots (recommended)**

**Example project (strongly recommended)**
[PongInJs.ict.zip](https://github.com/user-attachments/files/17630127/PongInJs.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment] 2024-11-08 21:09
Duplicate of #550

**Closed as not planned by CosmoMyzrailGorynych** 2024-11-08 21:09 UTC
Labels: state:duplicate, state:invalid

**Comment by CosmoMyzrailGorynych** [comment] 2024-11-08 21:15
The copy disappears because you assign an undefined variable. (Room's `test` is undefined during templates' Creation event as discussed in #550.) Invalid speed breaks position of the copy when it tries to move, making it impossible to render.

**Comment by 111ukasz111** [comment] 2024-11-09 13:59
> The copy disappears because you assign an undefined variable. (Room's `test` is undefined during templates' Creation event as discussed in #550.) Invalid speed breaks position of the copy when it tries to move, making it impossible to render.

I'm sorry for my stupidity.
